### ISSUE TITLE
Radare2 - NoneType' object has no attribute 'command'

### ISSUE THREAD

**Issue by 0xenigmark** [viper-framework/viper#620] opened 2017-11-25 03:27 UTC
master-malware-repo viper silent-army > r2 --help
usage: r2 [-h] [command [command ...]]

Start Radare2

positional arguments:
  command     Run a radare2 command on the current file

optional arguments:
  -h, --help  show this help message and exit

[!] The command r2 raised an exception:
Traceback (most recent call last):
  File "/home/user/viper/viper/core/ui/console.py", line 319, in start
    module.run()
  File "/home/user/viper/viper/modules/radare.py", line 35, in run
    r2command = ' '.join(self.args.command)
AttributeError: 'NoneType' object has no attribute 'command'

**Comment by frennkie** [comment] 2017-11-25 20:20
also this is a duplicate of #609

**Closed** 2017-11-28 13:34 UTC
