### ISSUE TITLE
broken yarascan, AttributeError: 'str' object has no attribute 'strings'

### ISSUE THREAD

**Issue by nefutpowers** [viper-framework/viper#419] opened 2016-02-26 15:52 UTC
Just cloned, fixed local issue stated in #418, and fixed files similar in #223 where .yara extension is not accepted. Tried running a YARA scan now and having - 

[*] Scanning xxxxxxx (xxxxxxx)
[!] The command yara raised an exception:
Traceback (most recent call last):
  File "<location>/viper/viper/core/ui/console.py", line 230, in start
    module.run()
  File "<location>/viper/viper/modules/yarascan.py", line 211, in run
    self.scan()
  File "<location>/viper/viper/modules/yarascan.py", line 139, in scan
    for string in match.strings:
AttributeError: 'str' object has no attribute 'strings'

Was this reported already/someone working on?

**Comment by botherder** [comment] 2016-02-29 19:04
Are you sure you have the latest version of Yara and the latest version of yara-python? It doesn't look like you do.

**Comment by ahhh** [comment] 2016-05-17 23:17
Experiencing the same issue:
Ubuntu 14.04.4 LTS
Yara 3.4.0
yara-python 3.4.0.00

Did you end up resolving the issue @nefutpowers ?

**Comment by botherder** [comment] 2016-05-22 20:14
I can't reproduce. Can any of you make sure you reinstall things properly? Delete the all yara related files from the Python libs folder and reinstall?

**Comment by pmelson** [comment] 2016-06-10 12:29
I had the same problem this morning.  Uninstalling, cleaning out /usr/local/lib/python2.7/yar*, and reinstalling yara-3.4.0 and yara-python (via pip) resolved the issue.

**Comment by Rafiot** [comment] 2017-02-24 13:24
Great, closing then.

**Closed by Rafiot** 2017-02-24 13:24 UTC
