### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by shibumi** [viper-framework/viper#476] opened 2016-11-13 02:03 UTC
Heyho,
I have packaged the current viper HEAD for the Arch Linux User Repository. During this process I got the following warning when starting viper:
```
/usr/lib/python2.7/site-packages/pymisp/api.py:14: UserWarning: You're using python 2, it is strongly recommended to use python >=3.3
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.3")
```

I would like to start a discussion. Wouldn't it be better if viper would migrate to python3? Or are some of the dependencies python2 only? I know at least from one: python-pype32

is there a way to supress this warnings? I don't want to scare users with it.

**Comment by Rafiot** [comment] 2016-11-14 11:36
I'm the maintainer of PyMISP, and this is kindof the point ;) 

Also, I'm not testing pymisp particularly thoughtfully on python 2.7 anymore so it may break. 

To make viper users happy, I can remove that warning, but I can also not ensure there won't be bugs on edge cases (encoding stuff that I seriously won't fix).

**Comment by shibumi** [comment] 2016-11-15 12:07
So the viper team should  think about moving to python3.. (except this would break other dependencies)

**Comment by Rafiot** [comment] 2016-11-15 16:30
I *think* the main packages blocking the move were the OLE* ones. And they are now supporting python3.

**Comment by Rafiot** [comment] 2017-02-16 13:24
Here is the current stats or the port: https://github.com/viper-framework/viper/pull/495

**Comment by Rafiot** [comment] 2017-02-25 23:23
(closing this one, duplicate of https://github.com/viper-framework/viper/issues/327)

**Closed by Rafiot** 2017-02-25 23:23 UTC
Labels: Encoding
