### ISSUE TITLE
viper-cli -h etc. borks on fresh install

### ISSUE THREAD

**Issue by pettai** [viper-framework/viper#471] opened 2016-10-16 19:45 UTC
```
~$ viper-cli -h
Traceback (most recent call last):
  File "/usr/local/bin/viper-cli", line 7, in <module>
    from viper.core.ui import console
  File "/usr/local/lib/python2.7/dist-packages/viper/core/ui/console.py", line 13, in <module>
    from viper.core.session import __sessions__
  File "/usr/local/lib/python2.7/dist-packages/viper/core/session.py", line 9, in <module>
    from viper.core.database import Database
  File "/usr/local/lib/python2.7/dist-packages/viper/core/database.py", line 19, in <module>
    from viper.core.project import __project__
  File "/usr/local/lib/python2.7/dist-packages/viper/core/project.py", line 48, in <module>
    __project__ = Project()
  File "/usr/local/lib/python2.7/dist-packages/viper/core/project.py", line 14, in __init__
    if cfg.paths.storage_path:
AttributeError: Config instance has no attribute 'paths'
```

Because .viper/viper.conf is empty on a fresh installation.
Perhaps capture the exception and generate a minimal/sample conf, or complain friendly that you'll have to fix a valid viper.conf before continuing...

**Comment by botherder** [comment] 2016-10-20 08:28
I can't reproduce that. When you launch viper-cli it should generate a new `~/.viper/viper.conf` file.
Can anybody else reproduce this?

**Comment by deralexxx** [comment] 2016-12-31 13:14
Hi @pettai thanks for the bug report, however I was unable to reprocude it as well.

Can you provide more specific infos about OS, python version used etc?

(Yes it has been a while and maybe your issues are already gone)

**Comment by Rafiot** [comment] 2017-02-24 13:02
Closing, please reopen if you still have the issue.

**Closed by Rafiot** 2017-02-24 13:02 UTC
Labels: Bug (to verify)
