### ISSUE TITLE
Email parse as an HTML file

### ISSUE THREAD

**Issue by coh7eiqu8thaBu** [viper-framework/viper#393] opened 2016-01-04 10:16 UTC
This eml file is reconized as a HTML file, and the parsing was erroneous
```
malware viper Payment Notification.eml > email -s
[*] Email spoof check:
+-------------+-------+
| Key         | Value |
+-------------+-------+
| Sender      |       |
| From        |       |
| Reply-To    |       |
| Return-Path |       |
+-------------+-------+
[!] No From address!
malware viper Payment Notification.eml > info
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Key      | Value                                                                                                                                         |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Name     | Payment Notification.eml                                                                                                                      |
| Tags     |                                                                                                                                               |
| Path     | /home/jpoggi/.montage_crypt/Securite/viper/projects/malware/binaries/6/e/9/f/6e9fec0c5ddd4eaca0f394c43d3e15c9cf22845d44cd3c0d2808d41d661719b5 |
| Size     | 123232                                                                                                                                        |
| Type     | HTML document, ASCII text, with very long lines, with CRLF line terminators                                                                   |
| Mime     | text/html; charset=us-ascii                                                                                                                   |
| MD5      | 3fcfd0356b90bce80cce2732e0e05a92                                                                                                              |
| SHA1     | e7449659938fae09bffec12963f884abca02d541                                                                                                      |
| SHA256   | 6e9fec0c5ddd4eaca0f394c43d3e15c9cf22845d44cd3c0d2808d41d661719b5                                                                              |
| SHA512   | 62e86a470de5f8db6f7070daea1cc6d738f9fa1ba6ab3e78a6bc396d4649ce7432067acb4cb88950dba84b7483d398e24d8de6c89ae5c9e59b8843e6092e6e4b              |
| SSdeep   | 1536:TFizERWlk3V874+9gdI+eekCCRdi7VLQN:TFiv4c/HRf                                                                                             |
| CRC32    | 6BBB2385                                                                                                                                      |
| Parent   |                                                                                                                                               |
| Children |                                                                                                                                               |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------+

```

[6e9fec0c5ddd4eaca0f394c43d3e15c9cf22845d44cd3c0d2808d41d661719b5.txt](https://github.com/viper-framework/viper/files/77042/6e9fec0c5ddd4eaca0f394c43d3e15c9cf22845d44cd3c0d2808d41d661719b5.txt)

**Comment by Rafiot** [comment] 2016-01-04 13:21
You have an extra `>` at the beginning of the file which make the parsing fail. 
It is still detected as HTML file because the mime checks are not 100% reliable but you will get all the information if you run `email -s`

**Comment by deralexxx** [comment] 2016-01-26 10:07
@coh7eiqu8thaBu do you feel we can close this issue?

**Comment by botherder** [comment] 2016-02-02 15:15
I'm closing it, @Rafiot seems to have pointed out it is not a bug.

**Closed by botherder** 2016-02-02 15:15 UTC
Labels: Bug (to verify)
